### ISSUE TITLE
VisUI & Libgdx 1.9.9 & DragAndDrop & null problem

### ISSUE THREAD

**Issue by KarolKasprzak** [kotcrab/vis-ui#309]
When i use 1.9.8 everything work fine, but after update libgdx to 1.9.9, every use of dragAndDrop in game end like this:  

Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.badlogic.gdx.scenes.scene2d.utils.DragAndDrop$1.drag(DragAndDrop.java:104)
	at com.badlogic.gdx.scenes.scene2d.utils.DragListener.touchDragged(DragListener.java:61)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:62)
	at com.badlogic.gdx.scenes.scene2d.Stage.touchDragged(Stage.java:314)
	at com.badlogic.gdx.InputMultiplexer.touchDragged(InputMultiplexer.java:135)
	at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:345)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:217)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by kotcrab** [comment]
Please provide [SSCCE](http://sscce.org/) and how to reproduce this issue.

**Comment by piotr-j** [comment]
DragAndDrop changed in 1.9.9, dragged actor is removed when its dragged. This caused me issues as well.

**Comment by kotcrab** [comment]
I'm not seeing any VisUI calls in the stack trace so not sure why this is reported here. IIRC VisUI doesn't even use `DragAndDrop` from libGDX.

**Comment by kotcrab** [comment]
Closing as no further explanation or example was provided.
