### ISSUE TITLE
VisUI is not loaded!

### ISSUE THREAD

**Issue by levymikael** [kotcrab/vis-ui#329]
Hey,
I am trying to use your library which seems amazing.but I keep having the same error msg:

Exception in thread "LWJGL Application" java.lang.IllegalStateException: VisUI is not loaded!
	at com.kotcrab.vis.ui.VisUI.getSkin(VisUI.java:125)
	at com.kotcrab.vis.ui.widget.VisTable.<init>(VisTable.java:32)
	at com.evalutel.primval_desktop.Sommaire.Screen_expandabletabletest.<init>(Screen_expandabletabletest.java:148)
	at com.evalutel.primval_desktop.Sommaire.Screen_Sommaire_General$4.clicked(Screen_Sommaire_General.java:217)

I am loading at the beginning of my class : 

        VisUI.load(); 

and dispose it at the end

Do I need to load a skin because I dont use at all.

Can you please assist ?

**Comment by kotcrab** [comment]
VisUI must be loaded before any widget is created and can't be unloaded until there are no instances of widgets (which is typically dispose method of the application). I recommend looking at the test file https://github.com/kotcrab/vis-ui/blob/master/ui/src/test/java/com/kotcrab/vis/ui/test/manual/TestLauncher.java which shows how to setup VisUI and scene2d.ui.
