### ISSUE TITLE
Textarea bug when a line is preceded by new line

### ISSUE THREAD

**Issue by fgnm** [kotcrab/vis-ui#336]
I've create a very simple textarea without any special stuff:

```Java
VisTextArea textArea = new VisTextArea("");
getContentTable().add(textArea).grow();
```
![textarea_bug](https://user-images.githubusercontent.com/5543339/91632627-6be0d980-e9e2-11ea-82d0-bdeda301d9ff.gif)

But I've a strange bug when I start typing after a new line. As you can see from the GIF, the cursor does not arrives at the end of the line, this is not just a visual bug, but causes also many crashes of that kind during selection or clicks in the textarea.
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 28 out of bounds for length 28
	at com.kotcrab.vis.ui.widget.VisTextField.calculateOffsets(VisTextField.java:259)
	at com.kotcrab.vis.ui.widget.VisTextArea.calculateOffsets(VisTextArea.java:283)
	at com.kotcrab.vis.ui.widget.VisTextField.draw(VisTextField.java:347)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:124)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:170)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:120)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:111)
	at com.badlogic.gdx.scenes.scene2d.ui.Window.draw(Window.java:252)
	at com.kotcrab.vis.ui.widget.VisWindow.draw(VisWindow.java:239)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:129)
```
Or this 

```
Caused by: java.lang.IndexOutOfBoundsException: index can't be >= size: 116 >= 114
	at com.badlogic.gdx.utils.FloatArray.get(FloatArray.java:131)
	at com.kotcrab.vis.ui.widget.VisTextArea.moveCursorLine(VisTextArea.java:164)
	at com.kotcrab.vis.ui.widget.VisTextArea$TextAreaListener.keyDown(VisTextArea.java:437)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:53)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
	... 10 more
```
I already use a mono spaced font generated from a TTF. Could you help me to identify the cause of that bug? Unfortunately, in test window I connot reproduce it.

**Comment by kotcrab** [comment]
I'd recommend first trying it with libgdx's `TextArea`, maybe some fix wasn't ported.

**Comment by fgnm** [comment]
Yes, I've tried with Scene2D's `TextArea` and same style I use for `VisTextArea` and this issue is not present, it works fine

**Comment by kotcrab** [comment]
So fixing this requires syncing sources of `VisTextField` and `VisTextArea` with libgdx.

**Comment by fgnm** [comment]
I've look at commits in libGDX and I've found that with this two the issue is fixed: https://github.com/libgdx/libgdx/commit/c2d2313717e90081f79eff7a982f601723be3777#diff-81602c9f8b4b94e2ec22c65427fbd35b and https://github.com/libgdx/libgdx/commit/b0d8a2be9a804201366c9bf4b620dba703360639#diff-81602c9f8b4b94e2ec22c65427fbd35b

There are also a lot of other commits that might be good (or not) for VisUI too, however I don't know if they may affects others `VisTextField` functionalities, so please let me know if you prefer a PR with that two changes or wait for a yours fix, thanks.

**Comment by kotcrab** [comment]
Looks like you already figured it out. I'd prefer a PR with those two fixes.
