### ISSUE TITLE
ToolTips not finding method "getListeners" in scene2D Actor

### ISSUE THREAD

**Issue by NullsByte** [kotcrab/vis-ui#346]
Example taken from Wiki.

gdxVersion 1.9.12
vis-ui 1.3.0
Windows 10 x64

Also occurs in a blank project - can anyone else verify this?
Code:
```
	VisLabel label = new VisLabel("Some Label");
	new Tooltip.Builder("this label has a tooltip").target(label).build();
```
Log:

Exception in thread "main" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchMethodError: 'com.badlogic.gdx.utils.Array com.badlogic.gdx.scenes.scene2d.Actor.getListeners()'
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:123)
	at sector.conflict.client.desktop.DesktopLauncher.main(DesktopLauncher.java:85)
Caused by: java.lang.NoSuchMethodError: 'com.badlogic.gdx.utils.Array com.badlogic.gdx.scenes.scene2d.Actor.getListeners()'
	at com.kotcrab.vis.ui.widget.Tooltip.attach(Tooltip.java:145)
	at com.kotcrab.vis.ui.widget.Tooltip.init(Tooltip.java:113)
	at com.kotcrab.vis.ui.widget.Tooltip.<init>(Tooltip.java:70)
	at com.kotcrab.vis.ui.widget.Tooltip.<init>(Tooltip.java:43)
	at com.kotcrab.vis.ui.widget.Tooltip$Builder.build(Tooltip.java:363)
	at sector.conflict.client.ui.RegisterWindow.lambda$new$0(RegisterWindow.java:38)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:157)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:117)
	... 1 more
Caused by: java.lang.NoSuchMethodError: 'com.badlogic.gdx.utils.Array com.badlogic.gdx.scenes.scene2d.Actor.getListeners()'

**Comment by NullsByte** [comment]
Vis UI version out of date...
