### ISSUE TITLE
Crash when trying to select in VisTextArea when libGDX color marckup is enabled

### ISSUE THREAD

**Issue by fgnm** [kotcrab/vis-ui#348]
`VisTextArea` and all its children (`HighlightTextArea`, `ScrollableTextArea`), crashes when [color markup](https://github.com/libgdx/libgdx/wiki/Color-Markup-Language) is enabled.

Stacktrace:
```
java.lang.IndexOutOfBoundsException: index can't be >= size: 1299 >= 1291
	at com.badlogic.gdx.utils.FloatArray.get(FloatArray.java:131)
	at com.kotcrab.vis.ui.widget.VisTextArea.drawSelection(VisTextArea.java:251)
	at com.kotcrab.vis.ui.widget.VisTextField.draw(VisTextField.java:350)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
	at com.badlogic.gdx.scenes.scene2d.ui.ScrollPane.draw(ScrollPane.java:543)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:124)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:170)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:126)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:117)
	at com.badlogic.gdx.scenes.scene2d.ui.Window.draw(Window.java:253)
	at com.kotcrab.vis.ui.widget.VisWindow.draw(VisWindow.java:239)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:111)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:58)
	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:129)
```
I think that `start` and `end` are not aware that markup glyphs are not rendered, and so the range is higher then the size of `glyphPositions` array
https://github.com/kotcrab/vis-ui/blob/8b997f2b64b0aeb308ab0442257294b03f8acf3e/ui/src/main/java/com/kotcrab/vis/ui/widget/VisTextArea.java#L247-L248

Where could be the right place to fix this? Thanks

**Comment by kotcrab** [comment]
LibGDX and VisUI doesn't support color markup for any text field iirc, see https://github.com/kotcrab/vis-ui/issues/313.
Can you reproduce this with libgdx's `TextArea`?

**Comment by fgnm** [comment]
`TextArea` don't work at all, I've got an empty rendering, while `VisTextArea` works overall well, it's broken just the selection, this is a screen of a `VisTextArea` rendering color markup string
![immagine](https://user-images.githubusercontent.com/5543339/103387309-36203e80-4b03-11eb-8def-3ecc619849d1.png)

It's a pity that VisUI not support color markup just for the this selection :smiley:

**Comment by kotcrab** [comment]
`VisTextArea` is mostly a copy of `TextArea` so something must have changed. I remember it working in `TextArea` (or `TextField`?) with issues.
I'm guessing fixing this requires parsing the text to remove color markup before it's used for selection and others functions. I'd nice if this was working in libGDX, I never wanted to change `VisTextArea` too much.
